"""Formal Sciences K3 - 17 specialties in 5 batches (4+4+3+3+3)."""

FORMAL_K3_BATCH1: dict[str, list[dict]] = {
    "formal_sciences_arithmetic_fundamentals": [
        {
            "title": "Number Systems and Properties Reference",
            "content": """# Number Systems and Properties Reference

## Number System Hierarchy
N (naturals) subset Z (integers) subset Q (rationals) subset R (reals) subset C (complex)

### Natural Numbers (N)
- 1, 2, 3, ...
- Peano axioms: 0 (or 1) is natural; successor of natural is natural; induction
- Well-ordering principle: every nonempty subset has least element
- Closure: +, * closed; - and / not always

### Integers (Z)
- ..., -2, -1, 0, 1, 2, ...
- Closure: +, -, * closed; / not always
- Division algorithm: a = bq + r, 0 <= r < |b|
- GCD: largest d dividing both a and b
  - Euclidean algorithm: gcd(a,b) = gcd(b, a mod b)
- LCM: smallest positive multiple of both

### Rational Numbers (Q)
- p/q where p, q in Z, q != 0
- Dense: between any two rationals is another rational
- Countable
- Decimal expansion: terminating or repeating

### Real Numbers (R)
- All numbers on real line
- Uncountable (Cantor's diagonal argument)
- Irrational: cannot be p/q (sqrt(2), pi, e)
- Decimal: non-terminating, non-repeating for irrationals
- Completeness: every bounded increasing sequence converges
- Least upper bound property

### Complex Numbers (C)
- a + bi where i^2 = -1
- Algebraically closed (Fundamental Theorem of Algebra)
- Magnitude: |a+bi| = sqrt(a^2 + b^2)
- Conjugate: a - bi
- Polar form: r(cos theta + i sin theta) = r e^(i theta) (Euler)
- De Moivre: (cos theta + i sin theta)^n = cos(n theta) + i sin(n theta)

## Properties of Operations
- Commutative: a + b = b + a; a * b = b * a
- Associative: (a + b) + c = a + (b + c); (a * b) * c = a * (b * c)
- Distributive: a * (b + c) = a*b + a*c
- Identity: a + 0 = a; a * 1 = a
- Inverse: a + (-a) = 0; a * (1/a) = 1 (a != 0)
- Cancellation: if a + c = b + c then a = b; if a*c = b*c and c != 0 then a = b

## Divisibility Rules
- 2: last digit even
- 3: digit sum divisible by 3
- 4: last two digits divisible by 4
- 5: last digit 0 or 5
- 6: divisible by 2 and 3
- 8: last three digits divisible by 8
- 9: digit sum divisible by 9
- 11: alternating digit sum divisible by 11

## Modular Arithmetic
- a = b (mod n) iff n | (a - b)
- (a + b) mod n = ((a mod n) + (b mod n)) mod n
- (a * b) mod n = ((a mod n) * (b mod n)) mod n
- Fermat's Little Theorem: a^(p-1) = 1 (mod p) for prime p, gcd(a,p)=1
- Euler's theorem: a^phi(n) = 1 (mod n) for gcd(a,n)=1
- Chinese Remainder Theorem: if gcd(m,n)=1, system x=a (mod m), x=b (mod n) has unique solution mod mn

## Common Pitfalls
- Dividing by zero (undefined)
- Assuming sqrt(a*b) = sqrt(a) * sqrt(b) for negative numbers
- Confusing rational with real
- Treating infinity as a number
- Ignoring domain restrictions (sqrt of negative, log of non-positive)
""",
            "tags": ["arithmetic", "number systems", "modular arithmetic", "divisibility", "reference"],
        }
    ],
    "formal_sciences_algebra": [
        {
            "title": "Linear and Abstract Algebra Reference",
            "content": """# Linear and Abstract Algebra Reference

## Linear Algebra

### Matrix Operations
- Addition: element-wise, same dimensions
- Multiplication: (m x n) * (n x p) = (m x p); (AB)_ij = sum_k A_ik B_kj
- Transpose: (A^T)_ij = A_ji
- Inverse: A^(-1) such that A A^(-1) = I; exists iff det(A) != 0
- Determinant: det(A) for 2x2 = ad - bc; recursive for larger

### Eigenvalues and Eigenvectors
- Av = lambda v
- Characteristic polynomial: det(A - lambda I) = 0
- Eigendecomposition: A = P D P^(-1) if diagonalizable
- Symmetric matrices: real eigenvalues, orthogonal eigenvectors
- SVD: A = U Sigma V^T (always exists)

### Vector Spaces
- Basis: linearly independent spanning set
- Dimension: size of basis
- Linear transformation: T(av + bw) = aT(v) + bT(w)
- Rank: dimension of image
- Nullity: dimension of kernel
- Rank-nullity theorem: rank + nullity = dim(domain)

### Key Theorems
- Cramer's rule: solve Ax = b using determinants
- Cayley-Hamilton: matrix satisfies its characteristic polynomial
- Spectral theorem: symmetric matrix orthogonally diagonalizable

## Abstract Algebra

### Groups
- (G, *): closure, associativity, identity, inverses
- Abelian: a*b = b*a
- Subgroup: H subset G, closed under * and inverse
- Order: |G| = number of elements
- Cyclic: generated by single element
- Cosets: aH = {ah : h in H}
- Lagrange's theorem: |H| divides |G|
- Normal subgroup: gH = Hg for all g
- Quotient group: G/H when H normal
- Homomorphism: f(a*b) = f(a) * f(b)
- Isomorphism: bijective homomorphism
- First Isomorphism Theorem: G/ker(f) = im(f)

### Rings
- (R, +, *): (R,+) abelian group, * associative, distributive
- Commutative ring: a*b = b*a
- Ring with identity: multiplicative identity 1
- Field: commutative ring with identity, every nonzero has inverse
- Ideal: subgroup I such that aI subset I and Ia subset I
- Principal ideal: generated by single element
- Z, Q, R, C are rings; Q, R, C are fields
- Z/nZ is field iff n is prime

### Examples
- S_n: symmetric group on n elements, order n!
- Z/nZ: integers mod n
- GL(n, F): invertible n x n matrices over field F
- Galois group: automorphisms of field extension

## Common Pitfalls
- Assuming matrix multiplication is commutative (AB != BA generally)
- Confusing rank with dimension
- Not checking if matrix is invertible
- Assuming all groups are abelian
- Confusing ring with field
""",
            "tags": ["algebra", "linear algebra", "groups", "rings", "matrices", "eigenvalues", "reference"],
        }
    ],
    "formal_sciences_geometry": [
        {
            "title": "Euclidean and Differential Geometry Reference",
            "content": """# Euclidean and Differential Geometry Reference

## Euclidean Geometry (Axioms)

### Euclid's Postulates
1. Straight line between any two points
2. Line segment can be extended
3. Circle with any center and radius
4. All right angles equal
5. Parallel postulate: through a point not on a line, exactly one parallel line

### Key Theorems
- Triangle angle sum: 180 degrees
- Pythagorean theorem: a^2 + b^2 = c^2 (right triangle)
- Similar triangles: corresponding angles equal, sides proportional
- Area: triangle = (1/2) b h; circle = pi r^2
- Circumference: C = 2 pi r

### Non-Euclidean Geometries
- Hyperbolic: no parallel lines through external point (infinite parallels)
  - Triangle angle sum < 180
  - Models: Poincare disk, upper half-plane
- Elliptic/Spherical: no parallel lines
  - Triangle angle sum > 180
  - Great circles as "lines"

## Differential Geometry

### Curves
- Parametric: r(t) = (x(t), y(t), z(t))
- Arc length: s = integral |r'(t)| dt
- Unit tangent: T = r'/|r'|
- Curvature: kappa = |T'| / |r'|
- Normal: N = T'/|T'|
- Binormal: B = T x N
- Torsion: tau = -B' . N / |r'|

### Surfaces
- Parametric: r(u, v)
- First fundamental form: E du^2 + 2F du dv + G dv^2 (metric)
- Second fundamental form: measures curvature
- Gaussian curvature: K = k1 * k2 (product of principal curvatures)
- Mean curvature: H = (k1 + k2) / 2
- Theorema Egregium (Gauss): K is intrinsic (preserved by bending)

### Manifolds
- Smooth manifold: locally like R^n with smooth transitions
- Tangent space: vectors at a point
- Riemannian metric: inner product on tangent spaces
- Geodesic: locally shortest path
- Connection: way to differentiate vector fields
- Curvature tensor: R(X,Y)Z = nabla_X nabla_Y Z - nabla_Y nabla_X Z - nabla_[X,Y] Z

## Coordinate Systems
- Cartesian: (x, y, z)
- Polar: (r, theta)
- Cylindrical: (r, theta, z)
- Spherical: (rho, theta, phi)
- Conversion formulas between systems

## Common Pitfalls
- Assuming Euclidean geometry is the only geometry
- Confusing intrinsic and extrinsic curvature
- Forgetting parallel postulate is independent (non-Euclidean geometries exist)
- Treating curvature as single number (it's a tensor)
""",
            "tags": ["geometry", "Euclidean", "differential", "curvature", "manifolds", "reference"],
        }
    ],
    "formal_sciences_trigonometry": [
        {
            "title": "Trigonometric Identities and Applications Reference",
            "content": """# Trigonometric Identities and Applications Reference

## Fundamental Identities

### Pythagorean
- sin^2(x) + cos^2(x) = 1
- tan^2(x) + 1 = sec^2(x)
- 1 + cot^2(x) = csc^2(x)

### Sum and Difference
- sin(A + B) = sin A cos B + cos A sin B
- sin(A - B) = sin A cos B - cos A sin B
- cos(A + B) = cos A cos B - sin A sin B
- cos(A - B) = cos A cos B + sin A sin B
- tan(A + B) = (tan A + tan B) / (1 - tan A tan B)
- tan(A - B) = (tan A - tan B) / (1 + tan A tan B)

### Double Angle
- sin(2x) = 2 sin x cos x
- cos(2x) = cos^2 x - sin^2 x = 2 cos^2 x - 1 = 1 - 2 sin^2 x
- tan(2x) = 2 tan x / (1 - tan^2 x)

### Half Angle
- sin(x/2) = +/- sqrt((1 - cos x) / 2)
- cos(x/2) = +/- sqrt((1 + cos x) / 2)
- tan(x/2) = (1 - cos x) / sin x = sin x / (1 + cos x)

### Product to Sum
- 2 sin A cos B = sin(A+B) + sin(A-B)
- 2 cos A sin B = sin(A+B) - sin(A-B)
- 2 cos A cos B = cos(A+B) + cos(A-B)
- 2 sin A sin B = cos(A-B) - cos(A+B)

### Sum to Product
- sin A + sin B = 2 sin((A+B)/2) cos((A-B)/2)
- sin A - sin B = 2 cos((A+B)/2) sin((A-B)/2)
- cos A + cos B = 2 cos((A+B)/2) cos((A-B)/2)
- cos A - cos B = -2 sin((A+B)/2) sin((A-B)/2)

## Laws for Triangles

### Law of Sines
- a/sin A = b/sin B = c/sin C = 2R (circumradius)

### Law of Cosines
- c^2 = a^2 + b^2 - 2ab cos C
- (Generalizes Pythagorean theorem)

### Law of Tangents
- (a - b)/(a + b) = tan((A-B)/2) / tan((A+B)/2)

### Area
- K = (1/2) ab sin C
- Heron's formula: K = sqrt(s(s-a)(s-b)(s-c)) where s = (a+b+c)/2

## Inverse Trigonometric Functions
- arcsin: domain [-1,1], range [-pi/2, pi/2]
- arccos: domain [-1,1], range [0, pi]
- arctan: domain R, range (-pi/2, pi/2)
- Derivatives: d/dx arcsin(x) = 1/sqrt(1-x^2); d/dx arctan(x) = 1/(1+x^2)

## Polar Coordinates
- x = r cos theta, y = r sin theta
- r = sqrt(x^2 + y^2), theta = arctan(y/x)
- Area in polar: (1/2) integral r^2 d theta

## Fourier Series
- f(x) = a0/2 + sum [a_n cos(nx) + b_n sin(nx)]
- a_n = (1/pi) integral f(x) cos(nx) dx
- b_n = (1/pi) integral f(x) sin(nx) dx
- Applications: signal processing, heat equation, vibration analysis

## Common Pitfalls
- Sign errors in sum/difference formulas
- Forgetting +/- in half-angle formulas (depends on quadrant)
- Confusing degrees and radians
- Not checking domain of inverse functions
- Assuming sin(A+B) = sin A + sin B (WRONG)
""",
            "tags": ["trigonometry", "identities", "law of sines", "law of cosines", "Fourier", "reference"],
        }
    ],
}

FORMAL_K3_BATCH2: dict[str, list[dict]] = {
    "formal_sciences_calculus": [
        {
            "title": "Calculus Rules and Techniques Reference",
            "content": """# Calculus Rules and Techniques Reference

## Differentiation Rules

### Basic
- d/dx (c) = 0
- d/dx (x^n) = n x^(n-1)
- d/dx (e^x) = e^x
- d/dx (a^x) = a^x ln(a)
- d/dx (ln x) = 1/x
- d/dx (sin x) = cos x
- d/dx (cos x) = -sin x
- d/dx (tan x) = sec^2 x
- d/dx (arcsin x) = 1/sqrt(1-x^2)
- d/dx (arctan x) = 1/(1+x^2)

### Rules
- Sum: (f + g)' = f' + g'
- Product: (fg)' = f'g + fg'
- Quotient: (f/g)' = (f'g - fg') / g^2
- Chain: (f(g(x)))' = f'(g(x)) g'(x)
- Implicit: differentiate both sides, solve for dy/dx

### Higher Derivatives
- f^(n)(x): nth derivative
- f'' > 0: concave up
- f'' < 0: concave down
- Inflection point: f'' = 0 (and changes sign)

## Integration Techniques

### Basic
- integral x^n dx = x^(n+1)/(n+1) + C (n != -1)
- integral 1/x dx = ln|x| + C
- integral e^x dx = e^x + C
- integral sin x dx = -cos x + C
- integral cos x dx = sin x + C
- integral sec^2 x dx = tan x + C

### Methods
- Substitution: integral f(g(x)) g'(x) dx = integral f(u) du
- By parts: integral u dv = uv - integral v du
- Partial fractions: decompose rational functions
- Trigonometric substitution: for sqrt(a^2 - x^2), sqrt(a^2 + x^2), sqrt(x^2 - a^2)

### Definite Integrals
- Fundamental Theorem: integral_a^b f(x) dx = F(b) - F(a) where F' = f
- Substitution in definite: change limits
- Properties: integral_a^b = -integral_b^a; integral_a^a = 0

## Series and Sequences

### Tests for Convergence
- Divergence test: if a_n -> 0 fails, series diverges
- Ratio test: lim |a_(n+1)/a_n| < 1 converges, > 1 diverges
- Root test: lim |a_n|^(1/n) < 1 converges
- Integral test: if f positive decreasing, sum and integral converge together
- Comparison test: compare to known series
- Alternating series test: decreasing to 0 -> converges

### Important Series
- Geometric: sum r^n = 1/(1-r) for |r| < 1
- p-series: sum 1/n^p converges iff p > 1
- Harmonic: sum 1/n diverges
- Alternating harmonic: sum (-1)^n/n converges

### Taylor Series
- f(x) = sum f^(n)(a)/n! * (x-a)^n
- e^x = sum x^n/n!
- sin x = sum (-1)^n x^(2n+1)/(2n+1)!
- cos x = sum (-1)^n x^(2n)/(2n)!
- Maclaurin: Taylor at a=0

## Multivariable Calculus

### Partial Derivatives
- f_x = delf/delx (y, z held constant)
- Gradient: grad f = (f_x, f_y, f_z)
- Directional derivative: D_u f = grad f . u
- Critical points: grad f = 0
- Second derivative test: D = f_xx f_yy - f_xy^2

### Multiple Integrals
- Double: integral integral f(x,y) dx dy
- Fubini: iterate integrals
- Polar: r dr d theta
- Triple: integral integral integral f(x,y,z) dx dy dz

### Vector Calculus
- Divergence: div F = Fx_x + Fy_y + Fz_z
- Curl: curl F = (Ry - Qz, Pz - Rx, Qx - Py) for F = (P, Q, R)
- Gradient: grad f
- Line integral: integral F . dr
- Green's theorem: oint F . dr = double integral (Qx - Py) dA
- Stokes' theorem: oint F . dr = double integral curl F . n dS
- Divergence theorem: oint F . n dS = triple integral div F dV

## Common Pitfalls
- Forgetting + C in indefinite integrals
- Wrong sign in integration by parts
- Not changing limits in substitution
- Confusing convergence tests
- Ignoring endpoints in Taylor series convergence
- Not checking critical points correctly
""",
            "tags": ["calculus", "derivatives", "integrals", "Taylor series", "vector calculus", "reference"],
        }
    ],
    "formal_sciences_mathematical_analysis": [
        {
            "title": "Real and Complex Analysis Reference",
            "content": """# Real and Complex Analysis Reference

## Real Analysis

### Limits
- epsilon-delta: for all epsilon > 0, exists delta > 0 such that |x-a| < delta implies |f(x)-L| < epsilon
- Sequential: f(x) -> L iff f(x_n) -> L for all x_n -> a

### Continuity
- f continuous at a: lim x->a f(x) = f(a)
- Uniform continuity: for all epsilon, exists delta for all x (delta independent of point)
- Intermediate Value Theorem: continuous f on [a,b] takes all values between f(a) and f(b)
- Extreme Value Theorem: continuous f on compact set attains max and min

### Differentiation
- Mean Value Theorem: f'(c) = (f(b)-f(a))/(b-a) for some c in (a,b)
- L'Hopital's rule: 0/0 or inf/inf -> lim f/g = lim f'/g'
- Taylor's theorem with remainder

### Integration
- Riemann: partition, upper/lower sums, limit
- Lebesgue: measure-based, more general
- Monotone convergence theorem
- Dominated convergence theorem
- Fubini's theorem: interchange order of integration

### Convergence
- Pointwise: f_n(x) -> f(x) for each x
- Uniform: sup |f_n - f| -> 0
- L^p: integral |f_n - f|^p -> 0
- Dini's theorem: monotone + compact + continuous -> uniform

### Important Spaces
- L^p: integrable functions with integral |f|^p finite
- C[a,b]: continuous functions on [a,b]
- l^p: sequences with sum |x_n|^p finite
- Banach space: complete normed vector space
- Hilbert space: complete inner product space

## Complex Analysis

### Holomorphic Functions
- f(z) differentiable in complex sense
- Cauchy-Riemann equations: u_x = v_y, u_y = -v_x (for f = u + iv)
- Holomorphic -> analytic (has power series)
- Entire: holomorphic on all of C

### Key Theorems
- Cauchy's integral theorem: integral over closed curve = 0 if f holomorphic inside
- Cauchy's integral formula: f(z) = (1/2pi i) oint f(w)/(w-z) dw
- Liouville's theorem: bounded entire function is constant
- Maximum modulus principle: |f| max on boundary
- Residue theorem: oint f(z) dz = 2pi i * sum residues

### Laurent Series
- f(z) = sum a_n (z-z0)^n (includes negative powers)
- Residue: coefficient of (z-z0)^(-1)
- Used to evaluate real integrals

### Conformal Mapping
- Analytic function with nonzero derivative preserves angles
- Mobius transformations: (az+b)/(cz+d)
- Riemann mapping theorem: simply connected proper subset of C conformally equivalent to disk

## Common Pitfalls
- Confusing pointwise and uniform convergence
- Not checking hypotheses of theorems (continuity, compactness)
- Assuming all functions are differentiable
- Forgetting branch cuts in complex functions (log, sqrt)
- Confusing holomorphic with real-differentiable
""",
            "tags": ["real analysis", "complex analysis", "limits", "holomorphic", "Cauchy", "reference"],
        }
    ],
    "formal_sciences_discrete_mathematics": [
        {
            "title": "Combinatorics and Graph Theory Reference",
            "content": """# Combinatorics and Graph Theory Reference

## Counting

### Basic Principles
- Multiplication: if task A has m ways, B has n ways, combined has mn
- Addition: if A or B (mutually exclusive), m + n ways
- Inclusion-exclusion: |A1 union A2| = |A1| + |A2| - |A1 intersect A2|
  - General: |union Ai| = sum |Ai| - sum |Ai intersect Aj| + ...

### Permutations and Combinations
- P(n, k) = n! / (n-k)!: ordered selection of k from n
- C(n, k) = n! / (k!(n-k)!): unordered selection
- With repetition: C(n+k-1, k): multiset of size k from n types
- Circular permutations: (n-1)!
- Derangements: !n = n! sum (-1)^k/k!

### Generating Functions
- Ordinary: G(x) = sum a_n x^n
- Exponential: E(x) = sum a_n x^n / n!
- Convolution: coefficients of product give sums of products

### Recurrence Relations
- Linear: a_n = c1 a_(n-1) + c2 a_(n-2) + ...
- Fibonacci: F_n = F_(n-1) + F_(n-2), F_0=0, F_1=1
- Solving: characteristic equation
- Master theorem: for T(n) = a T(n/b) + f(n)

## Graph Theory

### Definitions
- Graph G = (V, E): vertices V, edges E
- Directed (digraph): edges have direction
- Simple: no loops, no multiple edges
- Degree: number of edges at vertex
- Path: sequence of vertices connected by edges
- Cycle: path that starts and ends at same vertex
- Connected: path between any two vertices
- Tree: connected, acyclic
- Bipartite: vertices split into two sets, edges only between sets

### Key Theorems
- Handshaking lemma: sum of degrees = 2|E|
- Euler's formula: V - E + F = 2 (planar graphs)
- Kuratowski's theorem: non-planar iff contains K5 or K3,3 subdivision
- Four color theorem: planar graphs 4-colorable
- Konig's theorem: bipartite matching = vertex cover

### Important Graph Types
- Complete graph K_n: all pairs connected
- Bipartite K_{m,n}: two parts, all cross-edges
- Path graph P_n
- Cycle graph C_n
- Hypercube Q_n
- Petersen graph

### Algorithms
- BFS: shortest path (unweighted)
- DFS: traversal, connectivity
- Dijkstra: shortest path (non-negative weights)
- Bellman-Ford: shortest path (negative weights ok)
- Kruskal, Prim: minimum spanning tree
- Ford-Fulkerson: max flow
- Topological sort: DAG ordering

### Complexity
- NP-complete graph problems: Hamiltonian cycle, graph coloring, clique, TSP
- Polynomial: matching, shortest path, MST, flow

## Common Pitfalls
- Confusing permutations and combinations
- Not accounting for overcounting
- Forgetting graph must be connected for some theorems
- Assuming all graphs are planar
- Not checking if graph is directed vs undirected
""",
            "tags": ["discrete mathematics", "combinatorics", "graph theory", "counting", "reference"],
        }
    ],
    "formal_sciences_number_theory": [
        {
            "title": "Number Theory Theorems and Algorithms Reference",
            "content": """# Number Theory Theorems and Algorithms Reference

## Prime Numbers

### Distribution
- Prime Number Theorem: pi(x) ~ x / ln(x) as x -> infinity
  - pi(x) = number of primes <= x
- Bertrand's postulate: prime between n and 2n
- Twin primes: p, p+2 both prime; conjectured infinite
- Goldbach: every even > 2 = sum of two primes (conjecture)

### Tests
- Trial division: check up to sqrt(n)
- Miller-Rabin: probabilistic, fast
- AKS: deterministic, polynomial time
- Sieve of Eratosthenes: all primes up to n

## Modular Arithmetic

### Key Theorems
- Fermat's Little Theorem: a^(p-1) = 1 (mod p), p prime, gcd(a,p)=1
- Euler's theorem: a^phi(n) = 1 (mod n), gcd(a,n)=1
  - phi(n) = Euler's totient = count of 1 <= k <= n with gcd(k,n)=1
- Chinese Remainder Theorem: if gcd(m_i)=1, system x = a_i (mod m_i) has unique solution mod product m_i
- Wilson's theorem: (p-1)! = -1 (mod p) iff p prime

### Quadratic Reciprocity
- Legendre symbol (a/p) = 1 if a is QR mod p, -1 if not, 0 if p|a
- Euler's criterion: (a/p) = a^((p-1)/2) (mod p)
- Law: (p/q)(q/p) = (-1)^((p-1)/2 * (q-1)/2) for odd primes p, q
- Supplement: (-1/p) = (-1)^((p-1)/2); (2/p) = (-1)^((p^2-1)/8)

## Diophantine Equations

### Linear
- ax + by = c has solution iff gcd(a,b) | c
- Extended Euclidean algorithm finds solution

### Fermat's Last Theorem
- x^n + y^n = z^n has no positive integer solutions for n > 2
- Proved by Andrew Wiles (1995) using modularity theorem

### Pell's Equation
- x^2 - D y^2 = 1, D non-square
- Infinite solutions; fundamental solution generates all

## Cryptographic Applications

### RSA
- n = pq, phi = (p-1)(q-1)
- e with gcd(e, phi) = 1
- d = e^(-1) mod phi
- Encrypt: c = m^e mod n; Decrypt: m = c^d mod n
- Security: factoring n is hard

### Diffie-Hellman
- Public: p prime, g generator
- Alice: a secret, sends g^a
- Bob: b secret, sends g^b
- Shared: (g^a)^b = (g^b)^a = g^(ab)

### Elliptic Curve
- y^2 = x^3 + ax + b (mod p)
- Group law: geometric addition
- ECDLP: hard problem
- Smaller keys than RSA for same security

## Algorithms
- Euclidean: gcd(a, b) in O(log min(a,b))
- Extended Euclidean: gcd + Bezout coefficients
- Fast exponentiation: a^b mod n in O(log b)
- Miller-Rabin: primality in O(k log^3 n)

## Common Pitfalls
- Assuming primes are randomly distributed (they're not)
- Not checking gcd conditions in modular inverse
- Confusing Legendre with Jacobi symbol
- Using weak primes in RSA
- Not using secure random number generation
""",
            "tags": ["number theory", "primes", "modular arithmetic", "RSA", "cryptography", "reference"],
        }
    ],
}

FORMAL_K3_BATCH3: dict[str, list[dict]] = {
    "formal_sciences_topology": [
        {
            "title": "Point-Set and Algebraic Topology Reference",
            "content": """# Point-Set and Algebraic Topology Reference

## Point-Set Topology

### Topological Spaces
- (X, tau): set X with collection tau of open sets
- Axioms: empty and X open; arbitrary unions open; finite intersections open
- Closed: complement of open
- Basis: collection B such that every open set is union of basis elements

### Key Concepts
- Interior: largest open set contained in A
- Closure: smallest closed set containing A
- Boundary: closure minus interior
- Dense: A dense in X if closure(A) = X
- Limit point: every neighborhood intersects A in another point

### Continuity
- f: X -> Y continuous if preimage of open is open
- Homeomorphism: bijective, continuous, inverse continuous
- Homotopy equivalence: deformation retract

### Separation Axioms
- T0 (Kolmogorov): points distinguishable
- T1: singletons closed
- T2 (Hausdorff): distinct points have disjoint neighborhoods
- T3 (Regular): T1 + point and closed set separated
- T4 (Normal): T1 + disjoint closed sets separated

### Compactness
- Compact: every open cover has finite subcover
- Heine-Borel: in R^n, compact iff closed and bounded
- Sequentially compact: every sequence has convergent subsequence
- Locally compact: every point has compact neighborhood

### Connectedness
- Connected: not union of two disjoint nonempty open sets
- Path connected: path between any two points
- Components: maximal connected subsets

### Key Theorems
- Tychonoff: product of compact spaces is compact
- Urysohn's lemma: normal space, disjoint closed -> continuous function separating them
- Urysohn metrization: regular T1 + second countable -> metrizable
- Baire category: complete metric space is not countable union of nowhere dense

## Algebraic Topology

### Homotopy
- Homotopy: continuous family of maps f_t: X -> Y
- Homotopy relative to A: fixed on A
- Homotopy equivalence: f: X -> Y, g: Y -> X with gf ~ id_X, fg ~ id_Y
- Contractible: homotopy equivalent to point

### Fundamental Group
- pi_1(X, x0): loops at x0 modulo homotopy
- Group operation: concatenation of loops
- Basepoint independence if X path-connected
- Examples: pi_1(S^1) = Z; pi_1(S^n) = 0 for n >= 2; pi_1(torus) = Z x Z

### Covering Spaces
- p: E -> X covering map
- Universal cover: simply connected covering space
- Galois correspondence: subgroups of pi_1(X) <-> covering spaces

### Homology
- H_n(X): abelian groups measuring n-dimensional holes
- Chain complex: ... -> C_n -> C_(n-1) -> ...
- Boundary maps: delta_n delta_(n+1) = 0
- H_n = ker(delta_n) / im(delta_(n+1))
- Examples: H_0(X) = Z^k (k components); H_1(S^1) = Z; H_n(S^n) = Z

### Euler Characteristic
- chi = sum (-1)^n rank H_n(X)
- For finite CW complex: chi = sum (-1)^n (number of n-cells)
- chi(S^2) = 2; chi(torus) = 0

### Higher Homotopy Groups
- pi_n(X): maps from S^n to X modulo homotopy
- Abelian for n >= 2
- pi_n(S^n) = Z; pi_k(S^n) for k > n: complicated

## Common Pitfalls
- Confusing compact with closed and bounded (only in R^n)
- Assuming connected implies path connected (false in general)
- Forgetting basepoint matters for pi_1
- Confusing homotopy with homeomorphism
- Not checking all hypotheses of theorems
""",
            "tags": ["topology", "point-set", "algebraic topology", "fundamental group", "homology", "reference"],
        }
    ],
    "formal_sciences_logic": [
        {
            "title": "Formal Logic Systems Reference",
            "content": """# Formal Logic Systems Reference

## Propositional Logic

### Syntax
- Variables: p, q, r, ...
- Connectives: NOT (¬), AND (∧), OR (∨), IMPLIES (→), IFF (↔)
- Formulas: built recursively

### Semantics
- Truth values: T, F
- Truth tables define connectives
- Tautology: true under all assignments
- Satisfiable: true under some assignment
- Contradiction: false under all

### Equivalences
- De Morgan: ¬(p ∧ q) = ¬p ∨ ¬q; ¬(p ∨ q) = ¬p ∧ ¬q
- Double negation: ¬¬p = p
- Implication: p → q = ¬p ∨ q
- Contrapositive: p → q = ¬q → ¬p
- Distributive: p ∧ (q ∨ r) = (p ∧ q) ∨ (p ∧ r)

### Normal Forms
- DNF: disjunction of conjunctions
- CNF: conjunction of disjunctions
- Every formula has equivalent DNF and CNF

## First-Order Logic (Predicate Logic)

### Syntax
- Variables: x, y, z, ...
- Constants: a, b, c, ...
- Functions: f, g, ...
- Predicates: P, Q, R, ...
- Quantifiers: ∀ (for all), ∃ (there exists)
- Terms: variables, constants, function applications
- Formulas: atomic, negation, conjunction, quantification

### Semantics
- Structure M = (D, I): domain D, interpretation I
- M |= phi: M satisfies phi
- Valid: true in all structures
- Satisfiable: true in some structure

### Key Theorems
- Soundness: provable implies valid
- Completeness (Godel): valid implies provable
- Compactness: if every finite subset satisfiable, whole set satisfiable
- Lowenheim-Skolem: if satisfiable, has countable model

## Godel's Incompleteness Theorems

### First Incompleteness Theorem
- Any consistent formal system F capable of basic arithmetic:
  - There exists a statement G such that neither G nor ¬G is provable in F
- If F is consistent, it cannot prove its own consistency

### Second Incompleteness Theorem
- If F is consistent, F cannot prove Con(F) (a statement of F's consistency)

### Implications
- No complete consistent axiomatization of arithmetic
- Hilbert's program (prove all mathematics) impossible
- Some true statements are unprovable

## Modal Logic

### Systems
- K: basic modal logic with K axiom
- T: K + □p → p
- S4: T + □p → □□p
- S5: S4 + ◇p → □◇p

### Kripke Semantics
- Frame: (W, R): worlds W, accessibility R
- M, w |= □phi iff for all v with wRv, M, v |= phi
- M, w |= ◇phi iff exists v with wRv, M, v |= phi

### Applications
- Necessity and possibility
- Knowledge (epistemic logic)
- Belief (doxastic)
- Time (temporal logic)
- Programs (dynamic logic)

## Computability Theory

### Turing Machines
- Tape, head, states, transition function
- Church-Turing thesis: TM = effective computation
- Halting problem: undecidable (no TM solves it)

### Decidability
- Decidable: TM that always halts with yes/no
- Recognizable: TM that halts with yes for members
- Co-recognizable: complement recognizable

### Reductions
- A reduces to B: if we could solve B, we could solve A
- If B undecidable and A reduces to B, then A undecidable
- Many-one, Turing reductions

## Common Pitfalls
- Confusing syntax with semantics
- Thinking Godel means "truth is relative"
- Assuming all logics are classical
- Forgetting soundness vs completeness distinction
- Treating modal axioms as universal truths
""",
            "tags": ["logic", "propositional", "first-order", "Godel", "modal", "computability", "reference"],
        }
    ],
    "formal_sciences_probability": [
        {
            "title": "Probability Theory Reference",
            "content": """# Probability Theory Reference

## Axioms (Kolmogorov)
1. P(A) >= 0 for all events A
2. P(Omega) = 1
3. For disjoint A_i: P(union A_i) = sum P(A_i)

## Conditional Probability
- P(A|B) = P(A intersect B) / P(B), P(B) > 0
- Multiplication rule: P(A intersect B) = P(B) P(A|B)
- Law of total probability: P(A) = sum P(A|B_i) P(B_i) if B_i partition
- Bayes' theorem: P(B_i|A) = P(A|B_i) P(B_i) / P(A)

## Independence
- A, B independent: P(A intersect B) = P(A) P(B)
- Pairwise vs mutual independence
- Conditional independence: A ⊥ B | C

## Random Variables

### Discrete
- PMF: p(x) = P(X = x)
- Expected value: E[X] = sum x p(x)
- Variance: Var(X) = E[X^2] - (E[X])^2
- Standard deviation: sigma = sqrt(Var)

### Continuous
- PDF: f(x) with integral f = 1
- CDF: F(x) = P(X <= x) = integral_{-inf}^x f(t) dt
- E[X] = integral x f(x) dx
- Var(X) = integral (x - E[X])^2 f(x) dx

### Joint Distributions
- Joint PMF/PDF: p(x,y) or f(x,y)
- Marginal: p_X(x) = sum_y p(x,y)
- Conditional: p(x|y) = p(x,y) / p_Y(y)

## Common Distributions

### Discrete
- Bernoulli(p): X in {0,1}, P(1)=p; E=p, Var=p(1-p)
- Binomial(n,p): sum of n Bernoulli; E=np, Var=np(1-p)
- Geometric(p): trials until first success; E=1/p, Var=(1-p)/p^2
- Poisson(lambda): P(k) = e^{-lambda} lambda^k / k!; E=lambda, Var=lambda
- Negative Binomial(r,p): trials until r successes

### Continuous
- Uniform(a,b): f(x) = 1/(b-a); E=(a+b)/2, Var=(b-a)^2/12
- Normal(mu, sigma^2): f(x) = 1/(sigma sqrt(2pi)) e^{-(x-mu)^2/(2sigma^2)}
  - Standard: Z = (X-mu)/sigma ~ N(0,1)
  - 68-95-99.7 rule
- Exponential(lambda): f(x) = lambda e^{-lambda x}; E=1/lambda, Var=1/lambda^2
- Gamma(alpha, beta): generalization of exponential
- Beta(a, b): on [0,1]
- Chi-square(n): sum of n standard normals squared

## Limit Theorems

### Law of Large Numbers
- Weak: X_bar_n -> E[X] in probability
- Strong: X_bar_n -> E[X] almost surely

### Central Limit Theorem
- (X_bar_n - mu) / (sigma / sqrt(n)) -> N(0, 1)
- For n >= 30, X_bar approximately normal
- Applies to sums/averages of iid random variables

## Moment Generating Functions
- M(t) = E[e^{tX}]
- M^(k)(0) = E[X^k] (kth moment)
- Uniqueness: same MGF -> same distribution

## Common Pitfalls
- Confusing P(A|B) with P(B|A) (prosecutor's fallacy)
- Assuming independence without justification
- Forgetting CLT requires n large enough
- Misapplying Bayes' theorem (base rate neglect)
- Treating expected value as most likely value
""",
            "tags": ["probability", "distributions", "Bayes", "CLT", "random variables", "reference"],
        }
    ],
}

FORMAL_K3_BATCH4: dict[str, list[dict]] = {
    "formal_sciences_statistics": [
        {
            "title": "Statistical Inference Reference",
            "content": """# Statistical Inference Reference

## Estimation

### Point Estimation
- Estimator: function of sample estimating parameter
- Bias: E[theta_hat] - theta
- Unbiased: bias = 0
- Consistent: theta_hat -> theta as n -> infinity
- Efficiency: lower variance is better
- Cramer-Rao bound: minimum variance of unbiased estimator
- Method of moments: match sample and theoretical moments
- Maximum likelihood: maximize L(theta) = product f(x_i | theta)

### Interval Estimation
- Confidence interval: random interval containing parameter with probability 1-alpha
- For mean (known sigma): x_bar +/- z_{alpha/2} sigma / sqrt(n)
- For mean (unknown sigma): x_bar +/- t_{alpha/2, n-1} s / sqrt(n)
- For proportion: p_hat +/- z_{alpha/2} sqrt(p_hat(1-p_hat)/n)
- For variance: ((n-1)s^2 / chi^2_{alpha/2}, (n-1)s^2 / chi^2_{1-alpha/2})

## Hypothesis Testing

### Framework
- Null hypothesis H_0: default (often "no effect")
- Alternative H_1: what we're testing for
- Test statistic: function of data
- p-value: P(data as extreme | H_0 true)
- Significance level alpha: threshold for rejection (commonly 0.05)
- Reject H_0 if p < alpha

### Errors
- Type I: reject true H_0 (false positive); P = alpha
- Type II: fail to reject false H_0 (false negative); P = beta
- Power: 1 - beta (probability of correctly rejecting false H_0)

### Common Tests
- Z-test: mean, known sigma
- T-test: mean, unknown sigma (one-sample, two-sample, paired)
- Chi-square test: goodness of fit, independence
- F-test: comparing variances (ANOVA)
- Mann-Whitney U: nonparametric two-sample
- Wilcoxon: nonparametric paired
- Kolmogorov-Smirnov: distribution comparison

### Multiple Testing
- Bonferroni: divide alpha by number of tests
- False discovery rate (FDR): Benjamini-Hochberg
- Family-wise error rate: P(at least one Type I)

## Regression

### Linear Regression
- y = beta_0 + beta_1 x + epsilon
- Least squares: minimize sum (y_i - y_hat_i)^2
- beta_1 = Cov(x,y) / Var(x); beta_0 = y_bar - beta_1 x_bar
- R^2: proportion of variance explained
- Assumptions: linearity, independence, homoscedasticity, normality of residuals

### Logistic Regression
- Binary outcome: P(y=1) = 1/(1 + e^{-(beta_0 + beta_1 x)})
- Log-odds: log(p/(1-p)) = beta_0 + beta_1 x
- Maximum likelihood estimation
- No R^2; use pseudo-R^2, AIC

### Model Selection
- AIC: -2 log L + 2k (k = parameters)
- BIC: -2 log L + k log n
- Cross-validation: train/test split, k-fold
- Regularization: Lasso (L1), Ridge (L2), Elastic Net

## Bayesian Statistics

### Framework
- Prior: P(theta)
- Likelihood: P(data | theta)
- Posterior: P(theta | data) proportional to P(data | theta) P(theta)
- Predictive: P(x_new | data) = integral P(x_new | theta) P(theta | data) d theta

### Conjugate Priors
- Beta-Binomial: Beta prior, Binomial likelihood -> Beta posterior
- Gamma-Poisson: Gamma prior, Poisson likelihood -> Gamma posterior
- Normal-Normal: Normal prior, Normal likelihood -> Normal posterior

### MCMC
- Metropolis-Hastings: propose, accept/reject
- Gibbs sampling: sample each parameter conditional on others
- Stan, PyMC, JAGS: software implementations

## Common Pitfalls
- p-hacking: testing until significant
- Confusing statistical significance with practical significance
- Ignoring multiple testing
- Assuming causation from correlation
- Not checking regression assumptions
- Using small samples for large effect claims
- Misinterpreting confidence intervals (not probability parameter is in interval)
""",
            "tags": ["statistics", "inference", "hypothesis testing", "regression", "Bayesian", "reference"],
        }
    ],
    "formal_sciences_optimization": [
        {
            "title": "Optimization Methods Reference",
            "content": """# Optimization Methods Reference

## Linear Programming

### Standard Form
- minimize c^T x subject to Ax <= b, x >= 0

### Simplex Method
- Vertex of feasible polytope
- Move to adjacent vertex with better objective
- Pivot operations
- Terminates at optimal (or detects unbounded/infeasible)

### Duality
- Primal: min c^T x s.t. Ax >= b, x >= 0
- Dual: max b^T y s.t. A^T y <= c, y >= 0
- Strong duality: optimal values equal (if either finite)
- Complementary slackness: x_j (c_j - A_j^T y) = 0

### Interior Point Methods
- Polynomial time
- Karmarkar's algorithm (1984)
- Primal-dual methods

## Convex Optimization

### Convex Set
- For any x, y in C, tx + (1-t)y in C for t in [0,1]

### Convex Function
- f(tx + (1-t)y) <= t f(x) + (1-t) f(y)
- Local minimum = global minimum
- Second derivative >= 0 (for twice differentiable)

### Key Problems
- Linear programming (convex)
- Quadratic programming: min (1/2) x^T Q x + c^T x
- Second-order cone programming
- Semidefinite programming: min c^T x s.t. F(x) >= 0 (PSD)

### Gradient Descent
- x_{k+1} = x_k - alpha grad f(x_k)
- Convergence: O(1/k) for convex, O(1/sqrt(k)) for nonconvex
- Stochastic: use noisy gradient
- Mini-batch: balance noise and computation

### Newton's Method
- x_{k+1} = x_k - H^{-1} grad f
- Quadratic convergence near optimum
- Requires Hessian computation

### KKT Conditions
- For min f(x) s.t. g_i(x) <= 0, h_j(x) = 0:
  - grad f + sum lambda_i grad g_i + sum mu_j grad h_j = 0
  - lambda_i g_i = 0 (complementary slackness)
  - lambda_i >= 0
  - g_i <= 0, h_j = 0
- Necessary for optimality; sufficient if convex

## Integer Programming

### Branch and Bound
- Relax integrality, solve LP
- If solution non-integer, branch on fractional variable
- Bound: LP relaxation gives lower bound (minimization)
- Prune: if bound >= current best

### Cutting Planes
- Add constraints cutting off fractional solution
- Gomory cuts

## Combinatorial Optimization

### Problems
- TSP: visit all cities, minimize total distance (NP-hard)
- Minimum spanning tree: Kruskal, Prim (polynomial)
- Matching: maximum weight matching (polynomial)
- Knapsack: maximize value subject to weight (NP-hard)
- Set cover: cover universe with min sets (NP-hard)

### Approximation Algorithms
- TSP: Christofides 1.5-approximation (metric)
- Set cover: O(log n) approximation
- Vertex cover: 2-approximation

## Stochastic Optimization
- Robust optimization: worst-case over uncertainty set
- Stochastic programming: expected value over distribution
- Scenario-based: sample scenarios

## Common Pitfalls
- Not checking convexity (non-convex has local minima)
- Using gradient descent with wrong learning rate
- Not normalizing features
- Ignoring constraints
- Assuming simplex is polynomial (it's exponential worst-case)
- Not checking KKT conditions
""",
            "tags": ["optimization", "linear programming", "convex", "gradient descent", "KKT", "reference"],
        }
    ],
    "formal_sciences_numerical_methods": [
        {
            "title": "Numerical Algorithms Reference",
            "content": """# Numerical Algorithms Reference

## Floating-Point Arithmetic

### IEEE 754
- Single: 32 bits (1 sign, 8 exponent, 23 mantissa)
- Double: 64 bits (1 sign, 11 exponent, 52 mantissa)
- Machine epsilon: ~1.2e-7 (single), ~2.2e-16 (double)
- Roundoff: each operation introduces error ~epsilon
- Catastrophic cancellation: subtracting nearly equal numbers

### Conditioning
- Condition number: |delta output / output| / |delta input / input|
- Well-conditioned: small condition number
- Ill-conditioned: large (e.g., Hilbert matrix)
- Preconditioning: transform to improve conditioning

## Linear Algebra

### Solving Ax = b
- Gaussian elimination: O(n^3)
- LU decomposition: A = LU; solve Ly = b, Ux = y
- Cholesky: A = LL^T for symmetric positive definite
- QR: A = QR; solve Rx = Q^T b
- Iterative: Jacobi, Gauss-Seidel, SOR, Krylov (GMRES, CG)

### Eigenvalues
- Power iteration: dominant eigenvalue
- QR algorithm: iteratively find all eigenvalues
- Jacobi: for symmetric matrices
- Divide and conquer, Lanczos

### Least Squares
- Normal equations: A^T A x = A^T b (sensitive to conditioning)
- QR: solve R x = Q^T b (more stable)
- SVD: most stable, handles rank deficiency

## Interpolation

### Polynomial
- Lagrange: P(x) = sum y_i prod_{j != i} (x - x_j)/(x_i - x_j)
- Newton: divided differences
- Runge's phenomenon: oscillation at edges with high-degree equispaced

### Spline
- Cubic spline: piecewise cubic, C^2 continuous
- Natural: second derivative zero at endpoints
- Not-a-knot: alternative boundary

## Numerical Integration

### Newton-Cotes
- Trapezoidal: (h/2)(f_0 + 2f_1 + ... + 2f_{n-1} + f_n); O(h^2)
- Simpson's: (h/3)(f_0 + 4f_1 + 2f_2 + ... + 4f_{n-1} + f_n); O(h^4)
- Simpson's 3/8: O(h^4)

### Gaussian Quadrature
- Choose both nodes and weights
- Exact for polynomials up to degree 2n-1 (n points)
- Gauss-Legendre, Gauss-Hermite, Gauss-Laguerre

### Adaptive
- Subdivide where error estimate is large
- Recursive

## ODEs

### Initial Value Problems
- Euler: y_{n+1} = y_n + h f(t_n, y_n); O(h)
- Modified Euler (Heun): O(h^2)
- Runge-Kutta 4: O(h^4), most common
  - k1 = f(t, y); k2 = f(t + h/2, y + h k1/2); k3 = f(t + h/2, y + h k2/2); k4 = f(t + h, y + h k3)
  - y_{n+1} = y_n + (h/6)(k1 + 2k2 + 2k3 + k4)
- Adaptive: RK45 (Dormand-Prince)

### Stability
- Explicit: conditionally stable (small h needed for stiff)
- Implicit: unconditionally stable (solve nonlinear equations each step)
- Stiff ODEs: implicit methods (BDF, implicit Euler)

### Boundary Value Problems
- Shooting method: convert to IVP, iterate
- Finite difference: discretize, solve linear system
- Collocation: approximate with basis functions

## PDEs

### Finite Difference
- Replace derivatives with difference quotients
- Grid: x_i, t_n
- Stability: CFL condition
- Explicit vs implicit schemes

### Finite Element
- Weak form: integrate against test functions
- Mesh: elements with basis functions
- Assemble stiffness matrix and load vector
- Solve linear system

## Common Pitfalls
- Not checking for catastrophic cancellation
- Using unstable algorithms for stiff problems
- Too coarse grid (inaccurate) or too fine (slow)
- Not verifying convergence
- Ignoring boundary conditions
- Not testing on problems with known solutions
""",
            "tags": ["numerical methods", "floating point", "linear algebra", "ODE", "PDE", "reference"],
        }
    ],
}

FORMAL_K3_BATCH5: dict[str, list[dict]] = {
    "formal_sciences_computational_science": [
        {
            "title": "Computational Science Methods Reference",
            "content": """# Computational Science Methods Reference

## Modeling and Simulation

### Types of Models
- Deterministic: same input -> same output
- Stochastic: includes randomness
- Continuous: differential equations
- Discrete: cellular automata, agent-based
- Hybrid: multiple types combined

### Verification and Validation
- Verification: "solving equations right" (numerical correctness)
  - Code verification: compare to known solutions
  - Solution verification: estimate numerical error
- Validation: "solving right equations" (physical correctness)
  - Compare to experiments
  - Uncertainty quantification

### Uncertainty Quantification
- Forward: propagate input uncertainty through model
- Inverse: infer parameters from data (Bayesian, frequentist)
- Sensitivity analysis: how outputs vary with inputs
- Polynomial chaos expansion
- Monte Carlo sampling

## High-Performance Computing

### Parallel Programming
- MPI: message passing between processes
  - Send, receive, broadcast, reduce
  - Domain decomposition
- OpenMP: shared memory, threads
  - Parallel do, sections
- GPU (CUDA, OpenCL): thousands of cores
  - Kernels launched on device
  - Memory transfer is bottleneck
- Hybrid: MPI + OpenMP + CUDA

### Performance
- Roofline model: arithmetic intensity vs memory bandwidth
- Cache hierarchy: L1, L2, L3
- Vectorization: SIMD instructions
- Amdahl's law: speedup limited by serial fraction
- Gustafson's law: scaled speedup

## Domain Applications

### Computational Fluid Dynamics
- Navier-Stokes equations
- Discretization: finite difference, finite volume, finite element
- Turbulence: RANS, LES, DNS
- Mesh: structured, unstructured, adaptive

### Computational Chemistry
- Quantum chemistry: Schrodinger equation
  - Hartree-Fock, DFT
  - Basis sets: Gaussian, plane wave
- Molecular dynamics: classical forces
  - Force fields: AMBER, CHARMM, GROMOS
  - Integration: Verlet, leapfrog
- Free energy: umbrella sampling, metadynamics

### Computational Biology
- Protein folding: MD, coarse-grained
- Molecular docking: drug design
- Phylogenetics: tree reconstruction
- Genomics: sequence alignment, assembly

### Climate Modeling
- General circulation models
- Coupled atmosphere-ocean
- Parameterizations: subgrid processes
- Scenarios: IPCC pathways

## Visualization
- Scalar: color maps, isosurfaces, volume rendering
- Vector: streamlines, arrows, LIC
- Tensor: glyphs, hyperstreamlines
- Time-varying: animation
- Tools: ParaView, VisIt, VTK, matplotlib

## Software and Reproducibility
- Version control: git
- Containers: Docker, Singularity
- Workflow: Snakemake, Nextflow
- Documentation: reproducible reports
- Testing: unit tests, regression tests
- Data: HDF5, NetCDF, formats

## Common Pitfalls
- Not verifying numerical implementation
- Confusing model with reality
- Over-tuning parameters to match data
- Ignoring uncertainty in predictions
- Not testing parallel correctness
- Not profiling before optimizing
""",
            "tags": ["computational science", "simulation", "HPC", "verification", "visualization", "reference"],
        }
    ],
    "formal_sciences_operations_research": [
        {
            "title": "Operations Research Models Reference",
            "content": """# Operations Research Models Reference

## Linear Programming

### Formulation
- Decision variables: x_1, ..., x_n
- Objective: min c^T x or max c^T x
- Constraints: Ax <= b, x >= 0

### Examples
- Diet problem: minimize cost subject to nutritional requirements
- Transportation: minimize shipping cost from sources to destinations
- Assignment: assign workers to jobs minimizing cost

## Network Models

### Shortest Path
- Dijkstra: non-negative weights, O(V^2) or O(E + V log V) with heap
- Bellman-Ford: negative weights ok, O(VE)
- Floyd-Warshall: all pairs, O(V^3)

### Maximum Flow
- Ford-Fulkerson: augmenting paths
- Edmonds-Karp: O(VE^2)
- Min-cut max-flow theorem: max flow = min cut capacity

### Minimum Spanning Tree
- Kruskal: sort edges, add if no cycle; O(E log E)
- Prim: grow from vertex; O(E + V log V) with heap

### Transportation
- Northwest corner: initial feasible solution
- MODI: optimize
- Hungarian algorithm: assignment problem

## Integer Programming

### Formulation
- Variables restricted to integers (often binary)
- Branch and bound
- Cutting planes (Gomory)
- Branch and cut

### Applications
- Facility location: binary decisions
- Scheduling: assignment with constraints
- Knapsack: select items maximizing value

## Queueing Theory

### Notation (Kendall): A/B/c/K/N/D
- A: arrival distribution (M=Markov/Poisson)
- B: service distribution (M=exponential)
- c: servers
- K: capacity
- N: population
- D: discipline (FIFO)

### Key Formulas (M/M/1)
- rho = lambda / mu (utilization)
- L = rho / (1 - rho) (expected number in system)
- L_q = rho^2 / (1 - rho) (expected in queue)
- W = 1 / (mu - lambda) (expected time in system)
- W_q = rho / (mu - lambda) (expected wait)

### M/M/c
- Erlang C formula: probability of waiting
- L, L_q, W, W_q formulas more complex

## Inventory Theory

### EOQ (Economic Order Quantity)
- Q* = sqrt(2 K D / h)
- K: order cost, D: demand rate, h: holding cost

### Newsvendor
- Perishable product, single period
- Order quantity: F(Q*) = c_u / (c_u + c_o)
- c_u: underage cost, c_o: overage cost

### (s, S) Policy
- Order up to S when inventory drops to s
- Optimal for many inventory problems

## Game Theory

### Two-Person Zero-Sum
- Minimax theorem: max_x min_y x^T A y = min_y max_x x^T A y
- Solved by LP

### Nash Equilibrium
- No player benefits from unilateral deviation
- Existence: every finite game has one (Nash's theorem)
- Prisoner's dilemma: (Defect, Defect) is Nash but not Pareto optimal

### Cooperative
- Coalition formation
- Shapley value: fair allocation
- Core: stable allocations

## Markov Decision Processes

### Components
- States S, actions A
- Transition P(s' | s, a)
- Reward R(s, a, s')
- Policy pi: S -> A

### Solving
- Value iteration: V(s) = max_a sum P(s'|s,a) [R + gamma V(s')]
- Policy iteration: evaluate and improve
- Q-learning: model-free RL

## Common Pitfalls
- Not validating model assumptions
- Ignoring stochastic variability
- Over-optimizing for wrong objective
- Not considering robustness
- Confusing equilibrium with optimal
""",
            "tags": ["operations research", "linear programming", "queueing", "inventory", "game theory", "MDP", "reference"],
        }
    ],
    "formal_sciences_theoretical_computer_science": [
        {
            "title": "Complexity Classes and Algorithms Reference",
            "content": """# Complexity Classes and Algorithms Reference

## Asymptotic Notation
- O(f): upper bound
- Omega(f): lower bound
- Theta(f): tight bound
- o(f): strictly smaller
- Common: O(1), O(log n), O(n), O(n log n), O(n^2), O(2^n), O(n!)

## Complexity Classes

### Time Complexity
- P: solvable in polynomial time (n^k for constant k)
- NP: verifiable in polynomial time (certificate checked in poly time)
- NP-hard: at least as hard as any NP problem
- NP-complete: in NP and NP-hard
- coNP: complements of NP problems
- PSPACE: polynomial space
- EXPTIME: exponential time
- EXPSPACE: exponential space

### Known Relationships
- P subset NP subset PSPACE subset EXPTIME
- P subset EXPTIME (strict, by time hierarchy theorem)
- P vs NP: open (widely believed P != NP)

### Randomized
- BPP: bounded-error probabilistic polynomial time
- RP: one-sided error
- ZPP: zero error (Las Vegas)

### Quantum
- BQP: bounded-error quantum polynomial time
- Shor: factoring in BQP (not known NP-hard)
- Grover: search in O(sqrt(n))

### Space
- L: logarithmic space
- NL: nondeterministic logarithmic
- PSPACE: polynomial space
- Savitch's theorem: NSPACE(f) subset SPACE(f^2)

## NP-Complete Problems

### Classic
- SAT: satisfiability of Boolean formula (Cook-Levin)
- 3-SAT: 3 literals per clause
- CLIQUE: does graph have clique of size k?
- Vertex Cover: vertices covering all edges
- Hamiltonian Cycle: cycle visiting all vertices
- TSP (decision): tour of length <= k?
- Subset Sum: subset with sum = target?
- Graph Coloring: k-colorable?

### Reductions
- Cook-Levin: SAT is NP-complete (reduces any NP problem to SAT)
- 3-SAT <= CLIQUE <= Vertex Cover
- 3-SAT <= Hamiltonian Cycle <= TSP

## Algorithm Design Techniques

### Divide and Conquer
- Split, solve, combine
- Examples: merge sort O(n log n), quicksort O(n log n) avg
- Master theorem: T(n) = a T(n/b) + f(n)

### Dynamic Programming
- Overlapping subproblems, optimal substructure
- Memoization (top-down) or tabulation (bottom-up)
- Examples: Fibonacci, LCS, knapsack, edit distance

### Greedy
- Make locally optimal choice
- Works when greedy choice is globally optimal
- Examples: Huffman coding, Dijkstra, Kruskal, activity selection

### Backtracking
- Try options, undo if fail
- Examples: N-queens, Sudoku, SAT solvers

### Approximation
- For NP-hard problems
- PTAS: polynomial-time approximation scheme
- Examples: vertex cover 2-approx, TSP 1.5-approx (Christofides)

## Data Structures
- Array: O(1) access, O(n) insert
- Linked list: O(1) insert/delete, O(n) search
- Hash table: O(1) avg, O(n) worst
- Binary search tree: O(log n) avg, O(n) worst
- Balanced tree (AVL, red-black): O(log n) guaranteed
- Heap: O(log n) insert, O(1) min, O(log n) extract
- Union-Find: nearly O(1) amortized (with path compression)

## Common Pitfalls
- Assuming P = NP (open problem)
- Not analyzing average vs worst case
- Forgetting space complexity
- Using exponential algorithm when polynomial exists
- Not proving greedy choice property
- Confusing NP-hard with NP-complete
""",
            "tags": ["theoretical computer science", "complexity", "NP-complete", "algorithms", "reference"],
        }
    ],
}
