#!/usr/bin/env python3
"""Master orchestrator for the 4x A100 80GB training pipeline.

Runs the complete pipeline on 4x A100 80GB with DeepSpeed ZeRO-2:
  Pre-run:    Data generation (done locally with Gemini API — 20K pairs)
  Hours 0-13: Full fine-tune (02_finetune.py --gen 1, 4 epochs over 20K pairs)
  Hour 13:    Evaluate (03_evaluate.py --gen 1)
  Hour 14:    Convert to GGUF + quantize (05_convert_gguf.py --gen 1)

Hardware: 4x A100 80GB = 320 GB total VRAM
Method: Full fine-tuning with DeepSpeed ZeRO-2 + 8-bit AdamW
Data: 20,000 training pairs generated by Gemini from ANUBIS source material

Usage:
  python 00_master.py                    # Full pipeline (assumes data already uploaded)
  python 00_master.py --start-from finetune  # Resume from fine-tune
  python 00_master.py --start-from convert   # Resume from conversion

This script runs unattended. It logs every step and can resume from any stage.
"""
import json
import os
import sys
import time
import argparse
import subprocess
from pathlib import Path
from datetime import datetime

OUTPUT_DIR = Path("/workspace/training_output")
PIPELINE_DIR = Path(__file__).parent
STATE_FILE = OUTPUT_DIR / "pipeline_state.json"


def log(stage, msg, **kwargs):
    entry = {"timestamp": datetime.utcnow().isoformat(), "stage": stage, "message": msg, **kwargs}
    print(json.dumps(entry, default=str), flush=True)


def save_state(stage, data=None):
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    state = {}
    if STATE_FILE.exists():
        state = json.loads(STATE_FILE.read_text())
    state["last_stage"] = stage
    state["last_updated"] = datetime.utcnow().isoformat()
    if data:
        state.update(data)
    STATE_FILE.write_text(json.dumps(state, indent=2))


def load_state():
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text())
    return {}


def run_step(name, command, timeout_s=72000, use_deepspeed=False):
    """Run a pipeline step and track timing."""
    log("pipeline", f"Starting: {name}", command=command)
    start = time.time()

    # Ensure PYTHONPATH includes the repo root so anubis module is importable
    env = os.environ.copy()
    repo_root = str(Path(__file__).resolve().parent.parent.parent)
    env["PYTHONPATH"] = repo_root + os.pathsep + env.get("PYTHONPATH", "")
    env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

    # Use deepspeed launcher for training steps
    if use_deepspeed:
        cmd = ["deepspeed", "--num_gpus=4"] + [str(PIPELINE_DIR / command[0])] + command[1:]
    else:
        cmd = [sys.executable] + command

    result = subprocess.run(
        cmd,
        cwd=str(PIPELINE_DIR),
        timeout=timeout_s,
        capture_output=True,
        text=True,
        env=env,
    )

    duration = time.time() - start

    output_path = OUTPUT_DIR / f"log_{name}.txt"
    output_path.write_text(
        f"STDOUT:\n{result.stdout}\n\nSTDERR:\n{result.stderr}\n\n"
        f"Duration: {duration/60:.1f} minutes\n"
        f"Return code: {result.returncode}\n"
    )

    if result.returncode != 0:
        log("pipeline", f"FAILED: {name}", duration_minutes=duration/60,
            returncode=result.returncode, stderr=result.stderr[-500:])
        save_state(name, {"status": "failed", "error": result.stderr[-500:]})
        return False, duration

    log("pipeline", f"Completed: {name}", duration_minutes=duration/60)
    save_state(name, {"status": "completed", "duration_minutes": duration/60})
    return True, duration


def print_banner(title):
    print(f"\n{'='*60}", flush=True)
    print(f"  {title}", flush=True)
    print(f"{'='*60}\n", flush=True)


def main():
    parser = argparse.ArgumentParser(description="ANUBIS 4x A100 training pipeline")
    parser.add_argument("--start-from", type=str, default="finetune",
                       choices=["finetune", "evaluate", "convert"],
                       help="Stage to start from (for resume)")
    parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-32B-Instruct",
                       help="Base model to fine-tune")
    parser.add_argument("--quant", type=str, default="Q3_K_M",
                       help="GGUF quantization type")
    parser.add_argument("--data", type=str, default="/workspace/training_output/training_data_20k.jsonl",
                       help="Path to training data")
    args = parser.parse_args()

    pipeline_start = time.time()
    print_banner("ANUBIS 4x A100 Training Pipeline — 20K Pairs, Full Fine-Tune")
    log("pipeline", "Starting", model=args.model, start_from=args.start_from,
        gpu="4x A100 80GB", backend="DeepSpeed ZeRO-2 + 8-bit AdamW",
        data=args.data)

    # Pipeline stages
    # Data is generated locally and uploaded — no data gen stage here
    stages = [
        # (id, name, command, timeout_seconds, use_deepspeed)
        ("finetune", "Full Fine-tune (4 epochs over 20K pairs, DeepSpeed ZeRO-2)",
         ["02_finetune.py", "--gen", "1", "--data", args.data], 54000, True),  # 15 hours

        ("evaluate", "Evaluate Model (benchmarks + personality test)",
         ["03_evaluate.py", "--gen", "1"], 3600, False),  # 1 hour

        ("convert", "GGUF Conversion & Quantization for RTX 5060 Ti",
         ["05_convert_gguf.py", "--gen", "1", "--quant", args.quant, "--test"], 3600, False),
    ]

    # Determine starting index
    stage_names = [s[0] for s in stages]
    start_idx = stage_names.index(args.start_from)

    total_duration = 0
    completed = 0

    for i in range(start_idx, len(stages)):
        stage_id, stage_name, command, timeout, use_ds = stages[i]

        print_banner(f"Stage {i+1}/{len(stages)}: {stage_name}")

        # Estimate time remaining
        remaining_stages = stages[i:]
        est_remaining = sum(s[3] for s in remaining_stages) / 3600
        log("pipeline", f"Estimated time remaining: {est_remaining:.1f} hours")

        success, duration = run_step(stage_id, command, timeout_s=timeout, use_deepspeed=use_ds)
        total_duration += duration
        completed += 1

        if not success:
            log("pipeline", "Pipeline failed. Use --start-from to resume.",
                failed_stage=stage_id,
                completed_stages=completed,
                total_duration_hours=total_duration/3600)
            print(f"\n{'!'*60}")
            print(f"  PIPELINE FAILED AT: {stage_name}")
            print(f"  To resume: python 00_master.py --start-from {stage_id}")
            print(f"  Logs: {OUTPUT_DIR}/log_{stage_id}.txt")
            print(f"{'!'*60}")
            sys.exit(1)

        log("pipeline", f"Stage {i+1} complete",
            duration_minutes=duration/60,
            total_elapsed_hours=total_duration/3600)

    # Pipeline complete
    pipeline_duration = time.time() - pipeline_start
    print_banner("PIPELINE COMPLETE")

    # Load evaluation
    evaluation = {}
    eval_path = OUTPUT_DIR / "evaluation_gen1.json"
    if eval_path.exists():
        evaluation = json.loads(eval_path.read_text())

    # Load conversion metadata
    conv_meta = {}
    conv_path = OUTPUT_DIR / "gguf" / "conversion_metadata.json"
    if conv_path.exists():
        conv_meta = json.loads(conv_path.read_text())

    final_report = {
        "pipeline_complete": True,
        "total_duration_minutes": pipeline_duration / 60,
        "total_duration_hours": pipeline_duration / 3600,
        "stages_completed": completed,
        "base_model": args.model,
        "gpu": "4x A100 80GB",
        "method": "full_finetune_deepspeed_zero2_8bit_adamw",
        "training_pairs": 20000,
        "epochs": 4,
        "evaluation": evaluation,
        "conversion": conv_meta,
        "completed_at": datetime.utcnow().isoformat(),
    }

    report_path = OUTPUT_DIR / "final_report.json"
    report_path.write_text(json.dumps(final_report, indent=2))

    print(f"Total duration: {pipeline_duration/3600:.1f} hours")
    print(f"Stages completed: {completed}/{len(stages)}")

    if conv_meta:
        print(f"\nDeployment model: {conv_meta.get('quantized_path', 'unknown')}")
        print(f"Quantization: {conv_meta.get('quant_type', 'unknown')}")
        print(f"Size: {conv_meta.get('quantized_size_gb', 0):.1f} GB")
        print(f"Test passed: {conv_meta.get('test_passed', False)}")

    print(f"\nNext steps:")
    print(f"  1. Download the GGUF model from {OUTPUT_DIR}/gguf/")
    print(f"  2. Deploy on the RTX 5060 Ti")
    print(f"  3. Update ANUBIS config to use the new model")
    print(f"  4. Begin autonomous operation for Stage 5 progression")


if __name__ == "__main__":
    main()
